[package]
name = "space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6" }
bevy_prototype_debug_lines = { version = "0.6", features = ["3d"] }
lininterp = {}
big-brain = {}